<?php

declare(strict_types=1);

/**
 * @file
 * Provides a family node entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function ftree_core_theme(): array {
  return [
    'family_node' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for family node templates.
 *
 * Default template: family-node.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the family node information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_family_node(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function ftree_core_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_reassign':
      // Anonymize family nodes.
      $storage = \Drupal::entityTypeManager()->getStorage('family_node');
      $family_node_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($family_node_ids) as $family_node) {
        $family_node->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function ftree_core_user_predelete(UserInterface $account): void {
  // Delete family nodes that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('family_node');
  $family_node_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($family_node_ids)
  );
}
